[fix] Improvement/fixes for the python-related part of the code
- adds example python-only downstream progress reporting.
- separates the upstream python shared lib (for notebooks) into an *-extra package.

diff --git a/pynrm/Makefile b/pynrm/Makefile
--- a/pynrm/Makefile
+++ b/pynrm/Makefile
@@ -19,7 +19,12 @@ pre-commit: black
 .PHONY: black
 black:
 	@nix-shell --pure -p python37Packages.black --run bash <<< '
-	set -e
-	black bin/* --check
-	black nrm/*.py --check
+	RETURN=0
+	
+	black bin/* nrm/*.py extra/*.py --check
+	if [ $$? -ne 0 ]; then
+		echo "[!] Black format fail - Formatting.." >&2
+		black bin/* nrm/*.py extra/*.py
+		RETURN=1
+	fi
 	'
